import { expect, test } from '@playwright/test'
test('proformas and invoices have separate drafts, histories and WhatsApp messages',async({page},info)=>{
 const errors:string[]=[]
 page.on('pageerror',e=>errors.push(e.message))
 const writes:string[]=[]
 page.on('request',r=>{if(r.url().includes('/rest/v1/rpc/'))writes.push(r.url())})
 await page.goto('/demo/proformas')
 await expect(page.getByRole('heading',{name:'Proformas',exact:true})).toBeVisible()
 await expect(page.getByRole('button',{name:'Enviar proforma por WhatsApp',exact:true})).toBeDisabled()
 await page.getByLabel('Nombre del cliente',{exact:true}).fill('Cliente cotización')
 await page.getByRole('button',{name:'Agregar Producto A',exact:true}).click()
 await page.getByLabel('Cantidad de Producto A').fill('2')
 await page.getByRole('button',{name:'Guardar proforma',exact:true}).click()
 await expect(page.getByRole('heading',{name:'PROFORMA / COTIZACIÓN',exact:true})).toBeVisible()
 await expect(page.locator('.document-paper')).toContainText('DEMO-PRO-000001')
 await page.getByRole('button',{name:'Enviar proforma por WhatsApp',exact:true}).click()
 await expect(page.getByRole('dialog')).toBeVisible()
 await page.getByLabel('Número de WhatsApp').fill('88880000')
 const quoteURL=await page.getByRole('link',{name:'Abrir WhatsApp con proforma'}).getAttribute('href')
 const quoteText=new URL(quoteURL!).searchParams.get('text')!
 expect(quoteText).toContain('PROFORMA / COTIZACIÓN DEMO-PRO-')
 expect(quoteText).toContain('no es una factura')
 expect(quoteText).toContain('NIO 2500.00')
 await page.getByRole('button',{name:'Cerrar',exact:true}).click()
 await page.screenshot({path:'test-results/proformas-'+info.project.name+'.png',fullPage:true})
 // Use SPA navigation so the simulated document persists in the current session.
 await page.getByRole('navigation',{name:'Tipo de documento'}).getByRole('link',{name:'Facturación'}).click()
 await expect(page.getByLabel('Nombre del cliente',{exact:true})).toHaveValue('')
 await expect(page.getByText('Todavía no hay facturas.')).toBeVisible()
 await page.getByLabel('Nombre del cliente',{exact:true}).fill('Cliente factura')
 await page.getByRole('button',{name:'Agregar Producto B',exact:true}).click()
 await page.getByRole('button',{name:'Emitir factura',exact:true}).click()
 await expect(page.getByRole('heading',{name:'FACTURA',exact:true})).toBeVisible()
 await page.getByRole('button',{name:'Enviar factura por WhatsApp',exact:true}).click()
 await page.getByLabel('Número de WhatsApp').fill('+505 8888 0000')
 const invoiceURL=await page.getByRole('link',{name:'Abrir WhatsApp con factura'}).getAttribute('href')
 const invoiceText=new URL(invoiceURL!).searchParams.get('text')!
 expect(invoiceText).toContain('FACTURA DEMO-FAC-')
 expect(invoiceText).not.toContain('PROFORMA')
 await page.getByRole('button',{name:'Cerrar',exact:true}).click()
 await page.screenshot({path:'test-results/facturacion-'+info.project.name+'.png',fullPage:true})
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
 await page.getByRole('navigation',{name:'Tipo de documento'}).getByRole('link',{name:'Proformas'}).click()
 await expect(page.locator('.document-history')).toContainText('DEMO-PRO-000001')
 await expect(page.locator('.document-history')).not.toContainText('DEMO-FAC-')
 expect(writes).toEqual([])
 expect(errors).toEqual([])
})
